Add "Return YouTube Dislike" support and add video information to TV UI
lamarios/clipious pull request #154
Opened 2023-04-26 15:38 UTC by Outlet7493

* Add integration for https://returnyoutubedislike.com/ to all clients - this is off by default and can be enabled in settings - addresses https://github.com/lamarios/clipious/issues/17 if desired
* Add video info (views, likes, and publish text) to TV UI
- [x] I have updated the version and build number accordingly

2023-04-27 02:23 UTC, lamarios commented
Thanks ! I appreciate it. Since it is my first feature PR from someone I was wondering, is the code easy to understand and update ?

2023-04-27 09:17 UTC, lamarios requested changes
Tested it and it works great so far, only request is that we move the new setting in the browsing category instead of video player.

2023-04-27 10:30 UTC, Outlet7493 commented
Apologies, moved it to the browsing category now.

I added this feature with relative ease and it was pretty simple to find anything I did need! :smile:

2023-04-28 02:19 UTC, lamarios approved these changes

2023-04-28 02:19 UTC, lamarios commented
Thanks a lot !

2023-04-28 02:19 UTC, merged