More search filters and channel videos sorting options
lamarios/clipious pull request #411
Opened 2023-12-11 15:08 UTC by EgidioCaprino

This PR add more search filters in addition to the previous one: upload date and duration. It also add a dropdown button in the videos section of the channel screen, with sorting options: newest (default), oldest and popular

https://github.com/lamarios/clipious/assets/5156120/01c1a274-be87-457e-bbb5-644cac25ed03

2023-12-12 01:21 UTC, lamarios commented
fix #404

2023-12-12 01:24 UTC, lamarios commented
Thanks a lot again.  So far this looks pretty good but I feel like the channel video drop down looks quite out of place.  I don't have a good solution to that though. I was thinking change it to a button with a sort icon and just above the  video list, put a label with text style of label.small  showing what is the current sorting.

2023-12-12 07:36 UTC, EgidioCaprino commented
Hi @lamarios, thank you for the feedback. Do you have an example?

2023-12-12 07:39 UTC, lamarios commented
for the design itself, not really. for the text theming: https://github.com/lamarios/clipious/blob/master/lib/player/views/tv/components/player_controls.dart#L28  and applying it: https://github.com/lamarios/clipious/blob/master/lib/player/views/tv/components/player_controls.dart#L86  (The copy with is not necessary if you don't want to change anything)

2023-12-13 02:44 UTC, lamarios requested changes

2023-12-13 02:44 UTC, lamarios commented on lib/channels/models/channel_sort_by.dart
> +  String getLable(AppLocalizations locals) {
```suggestion
  String getLabel(AppLocalizations locals) {
```

2023-12-13 02:45 UTC, lamarios commented
Sorry i'll have to cause an annoyance to you, i want to merge my PR that changes most of the states and will create some conflicts for you. It should be easy to fix.

2023-12-13 08:01 UTC, lamarios commented
Mad eanother bunch of changes, i suggest you do a rebase on master branch, and also can you set up the pre-commit hooks

```
./submodules/flutter/bin/dart run tools/setup_git_hooks.dart
```
So that formatting rules and analysis are done before every commit

2023-12-14 09:37 UTC, lamarios commented
also fixes #166

2024-01-14 17:22 UTC, GitHubington commented
It would be nice to have an additional filter to distinguish the upload/broadcast states: pending, live, complete.

2024-01-15 08:33 UTC, lamarios approved these changes

2024-01-15 08:34 UTC, lamarios commented
I took the initiative to rebase your branch on master and fix some of the stuff.

2024-01-15 08:35 UTC, lamarios commented
> It would be nice to have an additional filter to distinguish the upload/broadcast states: pending, live, complete.

unfortunately this is not part of the invidious capabilities

2024-01-15 08:39 UTC, merged